# =========================================
# Global Configuration
# =========================================
global:
  paths:
    root_dir: /Users/paraspokharel/Programming/pitchProphet
    processed_dir: pitchProphet/data/pre_processing/processed  # processed data
    raw_dir: pitchProphet/data/fbref/raw # raw scrapped data
    model_dir: pitchProphet/models
    inf_raw_dir: pitchProphet/data/fbref/raw/inference # raw data for inference
    inf_out_dir: web/static/assets/tables # probability data from inference
    logs_dir: logs

# =========================================
# Data Collection Configuration
# =========================================
scraper:
  # API endpoints and identifiers
  base_url: "https://fbref.com/en/comps"
  league_ids:
    Premier-League: 9
    Bundesliga: 20
    Serie-A: 11
    League-1: 13
    La-Liga: 12

  # scraping parameters. format for league value should
  # be like scrapper[league_ids]'s keys. and the date 
  # should be in 20XX-20XX
  season: 2017-2018
  player_data: false
  league: Premier-League
  
  # rate limiting and retry logic
  rate_limit:
    sleep_range: [10, 15]  
    max_retries: 3         
    retry_delay: 600        

# =========================================
# Data Processing Configuration
# =========================================
processing:
  # feature window size
  last_n_match: 5

  # statistical features to calculate
  # TODO: make this configurable in the code
  aggregation_methods:
    - mean
    - sum
    - std
    - trend

  # variables to process
  x_vars:
    - Gls     # Goals -------Scoring Metrics------------
    - Ast     # Assists
    - PK      # Penalties
    - PKatt   # Penalty attempts
    - xG      # Expected goals
    - npxG    # Non-penalty xG
    - xAG     # Expected assisted goals
    - Sh      # Shots------  Shooting Metrics-----------
    - SoT     # Shots on target
    - CrdY    # Yellow cards--Disciplinary Metrics------
    - CrdR    # Red cards
    - Touches #--------   Possession Metrics------------
    - Carries 
    - PrgC    # Progressive carries
    - Cmp     # Passes completed
    - Att     # Passes attempted
    - Cmp%    # Pass completion %
    - PrgP    # Progressive passes
    - Tkl     # Tackles ------Devensive Metrics----------
    - Int     # Interceptions
    - Blocks
    - SCA     # Shot-creating actions--Creation Metrics---
    - GCA     # Goal-creating actions
    - Succ    # Successful actions

# =========================================
# Model Configuration
# =========================================
# TODO: make this configurable in the code
model:
  xgboost_params:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    objective: 'multi:softprob'
    num_class: 3
  
  train_test_split:
    test_size: 0.3
    random_state: 42

# =========================================
# Inference Configuration
# =========================================
inference:
  batch_size: 32
  update_frequency: 6  # Hours between updates
  prediction_threshold: 0.5

# =========================================
# Web Application Configuration
# =========================================
web:
  port: 5000
  debug: false
  paths:
    static: web/static
    templates: web/templates
    assets: web/static/assets